/** Sanity Icons v5: import from subpaths, re-export for schema convenience. */
export {BlockContentIcon} from '@sanity/icons/BlockContent'
export {BlockElementIcon} from '@sanity/icons/BlockElement'
export {BoltIcon} from '@sanity/icons/Bolt'
export {ChevronRightIcon} from '@sanity/icons/ChevronRight'
export {CommentIcon} from '@sanity/icons/Comment'
export {ComposeIcon} from '@sanity/icons/Compose'
export {DocumentIcon} from '@sanity/icons/Document'
export {DocumentTextIcon} from '@sanity/icons/DocumentText'
export {EnvelopeIcon} from '@sanity/icons/Envelope'
export {HomeIcon} from '@sanity/icons/Home'
export {ImageIcon} from '@sanity/icons/Image'
export {ImagesIcon} from '@sanity/icons/Images'
export {InlineIcon} from '@sanity/icons/Inline'
export {LinkIcon} from '@sanity/icons/Link'
export {UlistIcon as BulletOutlineIcon} from '@sanity/icons/Ulist'
export {MasterDetailIcon} from '@sanity/icons/MasterDetail'
export {MenuIcon} from '@sanity/icons/Menu'
export {NumberIcon} from '@sanity/icons/Number'
export {PackageIcon} from '@sanity/icons/Package'
export {SearchIcon} from '@sanity/icons/Search'
export {StackCompactIcon} from '@sanity/icons/StackCompact'
export {TextIcon} from '@sanity/icons/Text'
export {ThLargeIcon} from '@sanity/icons/ThLarge'
export {UserIcon} from '@sanity/icons/User'
export {UsersIcon} from '@sanity/icons/Users'
export {ColorWheelIcon} from '@sanity/icons/ColorWheel'
export {CogIcon} from '@sanity/icons/Cog'
